### ISSUE TITLE
McAfeeにてReputationが「High Risk」として登録されている

### ISSUE THREAD

**Issue by teppei696** [ehime-covid19/covid19#1]
## 起こっている問題 / The Problem
- McAfeeにてReputationが「High Risk」として検知されている
- ※既出であれば申し訳ありません。大阪版を作成している際、上記事象が発生し、McAfeeが入っている端末からアクセスできない事象が発生し、他のサイトでも同様の事象が起きていないかを見てみたところ、愛媛のサイトが同じ状況でしたので共有させていただきます。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/1694558/77129467-71cba980-6a97-11ea-8a45-cfaa8f232084.png)

## 期待する見せ方・挙動 / Expected Behavior
- Reputationが「Minimal Risk」として登録されている

## 起こっている問題の再現手段 / Steps to Reproduce
1. [Customer URL Ticketing System](https://www.trustedsource.org/en/feedback/url)を開く
2. 「McAfee SiteAdvisor/Web Control (Enterprise)」を選択し、「https://ehime-covid19.com/」を入力後、「Check URL」をクリック
![image](https://user-images.githubusercontent.com/1694558/77129668-282f8e80-6a98-11ea-9ff7-9e663c8be1a3.png)
3. チェック結果画面を確認

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by ehime-covid19** [comment]
ご指摘ありがとうございます
対応します。ありがとうございます！

**Comment by ehime-covid19** [comment]
何度かmcafeeに問い合わせを実施しMinimal Riskとなりました。
