### ISSUE TITLE
入院中・退院について（3/19現在）

### ISSUE THREAD

**Issue by imabari** [ehime-covid19/covid19#2]
## 起こっている問題 / The Problem
3/19現在1名入院、1名退院です

## 期待する見せ方・挙動 / Expected Behavior

愛媛県では資料は見つからなかったのですが

厚生労働省のこちらのPDFに
https://www.mhlw.go.jp/content/10900000/000610659.pdf

3/19現在　無症状病原体保有者を除く
現在1名入院、1名退院になっています

愛南町の方は無症状病原体保有者のためわかりませんが
おそらく退院されていると思います

**Comment by ehime-covid19** [comment]
ありがとうございます
知事の話では退院状況の公開はしないとなってたようなので、退院状況は厚生労働省の情報を見ないといけないのですね
修正しました
